version: '3'

services:
  minecraft-username-checker:
    build: .
    environment:
      - MINECRAFT_USERNAMES=<your_usernames_here>
      - DISCORD_WEBHOOK_URL=<your_discord_webhook_url_here>
      - DISCORD_USER_ID=<your_discord_user_id_here>
    volumes:
      - D:\GitLocal\minecraftNameTracker\:/app/