version: '3'

services:
  minecraft-username-checker:
    build: .
    environment:
      - MINECRAFT_USERNAMES=${MINECRAFT_USERNAMES}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DISCORD_USER_ID=${DISCORD_USER_ID}
      - BUILD=1 # remove this line
    volumes:
      - ./:/app/