name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo $GH_PAT | docker login ghcr.io --username itslightmind --password-stdin
      
      - name: Build and push the image
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker build . --file Dockerfile --tag ghcr.io/itslightmind/jncep-web-service:latest --tag ghcr.io/itslightmind/jncep-web-service:$GITHUB_SHA
          docker push ghcr.io/itslightmind/jncep-web-service:latest
          docker push ghcr.io/itslightmind/jncep-web-service:$GITHUB_SHA
      
      - name: Run Docker Compose
        env:
          MINECRAFT_USERNAMES: ${{ secrets.MINECRAFT_USERNAMES }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          BUILD: ${{ secrets.BUILD }}
        run: |
          docker-compose up --build -d
          docker-compose logs -f
