name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        env:
          MINECRAFT_USERNAMES: ${{ secrets.MINECRAFT_USERNAMES }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          BUILD: ${{ secrets.BUILD }}
        run: |
          docker-compose up --build -d
          docker-compose logs -f