name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose logs -f